spec-version: 0.36.0

name: ghc-bench
version: 0.2.0
synopsis: Benchmark a Haskell development system
description: See the README at <https://github.com/sol/ghc-bench#readme>
author: Simon Hengel <sol@typeful.net>
github: sol/ghc-bench
category: Development

ghc-options: -Wall

language: GHC2024

default-extensions:
 - NoImplicitPrelude
 - OverloadedStrings
 - RecordWildCards
 - ViewPatterns
 - BlockArguments
 - LambdaCase
 - NoFieldSelectors
 - DuplicateRecordFields
 - OverloadedRecordDot
 - DerivingStrategies

dependencies:
  - base == 4.*
  - bytestring
  - directory
  - filepath
  - process
  - text
  - temporary
  - http-types

source-dirs: src

executable:
  main: Main.hs
  source-dirs: driver

tests:
  spec:
    cpp-options: -DTEST
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec == 2.*
      - yaml
      - containers
      - silently
