title    Arch Linux install medium (%ARCH%, UEFI) (dvorak keymap)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=4G vconsole.keymap=dvorak
