name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ghc:
          - '9.10'
          - '9.12'
          - '9.14'
    steps:
      - uses: actions/checkout@v5
      - uses: hspec/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal update
      - run: cabal build all --dry-run -v0

      - run: echo "version=`ghc --numeric-version`" >> $GITHUB_OUTPUT
        id: ghc

      - run: echo "store-dir=`cabal -v0 path --store-dir`" >> $GITHUB_OUTPUT
        id: cabal-path

      - uses: actions/cache/restore@v3
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.ghc.outputs.version }}
        with:
          path: ${{ steps.cabal-path.outputs.store-dir }}
          key: ${{ env.key }}-${{ hashFiles('dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ env.key }}-

      - run: cabal build all --only-dependencies

      - uses: actions/cache/save@v3
        with:
          path: ${{ steps.cabal-path.outputs.store-dir }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
        if: steps.cache.outputs.cache-hit != 'true'

      - run: cabal build all
      - run: cabal test spec --test-show-details=direct

  success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: false
        if: needs.build.result != 'success'

      - uses: actions/checkout@v4
      - name: Check for trailing whitespace
        run: '! git grep -I "\s\+$"'

      - run: curl -sSL https://raw.githubusercontent.com/sol/hpack/main/get-hpack.sh | bash
      - run: hpack && git diff --exit-code
