name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ghc: 9.12.4
    steps:

      - uses: actions/checkout@v5
      - uses: hspec/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: rm cabal.project

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git tar bsdtar binutils autoconf make xz zstd
            curl automake p7zip patch m4
            mingw-w64-clang-x86_64-ca-certificates
            mingw-w64-clang-x86_64-gcc
            mingw-w64-clang-x86_64-python3
            mingw-w64-clang-x86_64-python-sphinx
            mingw-w64-clang-x86_64-tools-git
            mingw-w64-clang-x86_64-ca-certificates
      - run: C:\msys64\msys2_shell.cmd -mingw64 -use-full-path -defterm -no-start -here -c 'echo $PATH'
      - run: C:\msys64\msys2_shell.cmd -mingw64 -use-full-path -defterm -no-start -here -c 'echo $PATH'

      - name: Get sources
      - run: |
          curl "https://downloads.haskell.org/~ghc/9.12.4/ghc-9.12.4-src.tar.gz" -o ghc-9.12.4-src.tar.gz
          curl "https://downloads.haskell.org/~ghc/9.12.4/ghc-9.12.4-windows-extra-src.tar.gz" -o ghc-9.12.4-windows-extra-src.tar.gz
          curl "https://downloads.haskell.org/~ghc/9.12.4/ghc-9.12.4-testsuite.tar.gz" -o ghc-9.12.4-testsuite.tar.gz
          tar -xf ghc-9.12.4-src.tar.gz
          tar -xf ghc-9.12.4-windows-extra-src.tar.gz
          tar -xf ghc-9.12.4-testsuite.tar.gz

      - name: Configure
        run: C:\msys64\msys2_shell.cmd -mingw64 -use-full-path -defterm -no-start -here -c './configure --enable-tarballs-autodownload'
        working-directory: ghc-9.12.4

      - name: Make sure that Hadrian is built
        run: |
          cabal update
          C:\msys64\msys2_shell.cmd -mingw64 -use-full-path -defterm -no-start -here -c 'hadrian/build.bat -j4 --help'
        working-directory: ghc-9.12.4

      - name: Build GHC
        run: C:\msys64\msys2_shell.cmd -mingw64 -use-full-path -defterm -no-start -here -c 'hadrian/build.bat -j4 --flavour=quickest'
        working-directory: ghc-9.12.4
