name: Build ISO

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - iso-image
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - run: pacman -Sy git github-cli sudo archiso base-devel --noconfirm
      - run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v6
        with:
          ref: iso-image
      - name: Install cabal-install
        run: |
          curl https://downloads.haskell.org/~cabal/cabal-install-3.16.1.0/cabal-install-3.16.1.0-x86_64-linux-rocky8.tar.xz | tar -xJ
          mv cabal /usr/local/bin
      - run: cabal update
      - run: useradd -m -G wheel -s /bin/bash makepkg
      - run: sudo -u makepkg make /tmp/ghc-bench/live/pacman/ghc-bin-9.12.4-1-x86_64.pkg.tar.zst
      - run: pacman -U /tmp/ghc-bench/live/pacman/ghc-bin-9.12.4-1-x86_64.pkg.tar.zst --noconfirm
      - run: make airootfs/usr/local/bin/cabal
      - run: make airootfs/usr/local/bin/ghc-bench
      - run: make airootfs/root/.cache/cabal
      - run: make airootfs/root/.cache/ghc-bench
      - run: pacman -Rns ghc-bin --noconfirm
      - run: rm -r ~/.local/
      - run: rm -r ~/.cache/
      - run: make iso
      - name: publish
        run: |
          gh release create live-iso-image || (git tag live-iso-image -f && git push --tags -f)
          gh release upload live-iso-image /tmp/ghc-bench/live/out/ghc-bench-live-latest-x86_64.iso --clobber
        env:
          GH_TOKEN: ${{ github.token }}
      - run: sha256sum /tmp/ghc-bench/live/out/ghc-bench-live-latest-x86_64.iso
